fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.3.1
    epel:
      repo: https://github.com/stahnma/puppet-module-epel.git
      ref: 1.0.0
    augeasproviders_core:
      repo: https://github.com/hercules-team/augeasproviders_core.git
    augeasproviders_shellvar:
      repo: https://github.com/hercules-team/augeasproviders_shellvar.git
    yum:
      repo: https://github.com/CERIT-SC/puppet-yum.git
  symlinks:
    zfsonlinux: "#{source_dir}"
