fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.3.1
    gpg_key:
      repo: git://github.com/treydock/puppet-gpg_key.git
      ref: 0.0.3
    epel:
      repo: git://github.com/stahnma/puppet-module-epel.git
      ref: 1.0.0
  symlinks:
    zfsonlinux: "#{source_dir}"
