name    'treydock-zfsonlinux'
version '0.0.2'
source 'git://github.com/treydock/puppet-zfsonlinux.git'
author 'treydock'
license 'Apache License, Version 2.0'
summary 'zfsonlinux puppet module'
description 'zfsonlinux puppet module'
project_page 'http://github.com/treydock/puppet-zfsonlinux'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'treydock/gpg_key', '0.x'
dependency 'stahnma/epel', '0.x'
dependency 'domcleal/augeasproviders', '1.x'
